name: Build APK File
on:
  pull_request:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  Setup-Environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Job 1
        id: j1
        run: cd a
        continue-on-error: true

      - name: Job 2
        id: j2
        run: cd app
        continue-on-error: true

      - name: Job 3
        id: j3
        run: cd b
        continue-on-error: true

      - name: Comment Report
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.github_token }}
          script:  |
            const fs = require('fs');
            const resultSuccess = "✅ Success";
            const resultFailure = "❌ Failure";

            const detektReportFilePath = 'detekt/report/detekt_report.md';
            const detektReport = "Detekt report here";
            const detektResult = ${{steps.j1.outcome}}.toString() == 'success' ? resultSuccess : resultFailure;

            const lintReportFilePath = 'app/build/reports/lint-results-debug.html';
            const lintReport = "Lint report here"
            const lintResult =  resultFailure;

            const commentBody = `
            ### Code Analysis Summary
            | Test | Result |
            | --- | --- |
            | Detekt | ${detektResult} |
            | Lint | ${lintResult} |

            ### Detail Report

            <details>
            <summary>Detekt full report</summary>
            ${detektReport}
            </details>

            <details>
            <summary>Lint full report</summary>
            ${lintReport}
            </details>

            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
