  name: Build APK File
  on:
    push:
      branches:
        - 'feat/pr_comment'
  concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

  jobs:
    Setup-Environment:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

#        - name: Setup Java
#          uses: actions/setup-java@v1
#          with:
#            java-version: "11"

#        - name: Build Android APK
#          run: ./gradlew assembleDebug --stacktrace

#        - name: Upload build
#          uses: actions/upload-artifact@v3
#          with:
#            name: debug-build
#            path: app/build/outputs/apk/debug/app-debug.apk

        - name: Job 1
          id: j1
          run: cd a
          continue-on-error: true

        - name: Job 2
          id: j2
          run: cd app
          continue-on-error: true


        - name: Job 3
          id: j3
          run: cd b
          continue-on-error: true

        #
#        - name: Run Android lint
#          id: lint
#          run: ./gradlew lint
#          continue-on-error: true

        - name: Comment Report
#          if: steps.lint.outcome != 'success'
          uses: actions/github-script@v4
          with:
            github-token: ${{ secrets.github_token }}
            script: |
              let status1 = ${{steps.j1.outcome}};
#              var status2 = ${{steps.j2.outcome}}
#              var status3 = ${{steps.j3.outcome}}
              github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '
              test only
              multiline'
               });
